### ISSUE TITLE
Teams::role is undefined

### ISSUE THREAD

**Issue by buzzclue** [Jurager/teams#12]
This package looks promising and has everything, in simple words the most complete package but things aren't working either the read me isn't updated or maybe I have missed something.

```php
Teams::defaultApiTokenPermissions(['read']);
    
Teams::role('admin', 'Administrator', [
    'server:create',
    'server:read',
    'server:update',
    'server:delete',
])->description('Administrator users can perform any action.');

Teams::role('support', 'Support Specialist', [
    'server:read',
])->description('Support specialists can read server information.');
```

In `TeamsServiceProvider`, not able to define role, 

```php
Ability::firstOrCreate([ 'name' => 'edit', 'title' => 'Edit' ]);
```
Doesn't work either the team_id is missing. How can one define global roles and abilities for teams?

If you could setup a demo app I can help you write documentation? plus demo app will be helpful understanding the lifecycle and flow of package?

**Comment by Jurager** [comment]
@buzzclue I'll try to provide a demo as soon as I have some time. As for the problem, I slightly updated the documentation to make it clearer, cause the actual branch 2.0 had a lot of changes in working with roles/permissions etc, branch 1.0 will be soon deleted, when our internal project will be migrated to 2.0.

**Comment by Jurager** [comment]
@buzzclue, in current master (2.0) branch, all information about roles/permissions etc. are stored in database not in AppServiceProvider, for extensibility reasons, please refer to https://github.com/Jurager/teams#roles--permissions, if you have any questions feel free to ask

**Comment by buzzclue** [comment]
Thank you for your prompt response
