### ISSUE TITLE
More info for Group model

### ISSUE THREAD

**Issue by fermevc** [Jurager/teams#18]
Can you please explain the logic behind "group" relationship. I'm trying to make some basic "CRUD" GUI for this package in order to test everything and to understand how everything works, but got stuck with 'Class "App\Models\Group" not found' error because of eager loaded relation in 'Team' class... TBH, I'm a noob when it comes to digging into PHP/Laravel OO code, I'm hoping that you'll be able to give us some more examples/docs soon. Thanks in advance!

**Comment by ZebTheWizard** [comment]
Ran into the same problem, after digging through the code, it looks like we are expected to provide our own `App\Models\Group` model and a few other models.

We can specify which model to use by adding config methods to the `TeamServiceProvider` that was generated after running `php artisan teams:install`

Make sure to add the TeamServiceProvider to you config/app.php

I extended the default behavior by making my TeamServiceProvider look like this:

the config values are kind of redundant though.
```
class TeamsServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
	Teams::useMembershipModel(config('teams.models.membership', Membership::class));
	Teams::useTeamModel(config('teams.models.team', Team::class));
	Teams::useUserModel(config('teams.models.user', User::class));
	Teams::useAbilityModel(config('teams.models.ability', Ability::class));
        Teams::usePermissionModel(config('teams.models.permission', Permission::class));
        Teams::useGroupModel(config('teams.models.group', Group::class));
        Teams::useRoleModel(config('teams.models.role', Role::class));
        Teams::useCapabilityModel(config('teams.models.capability', Capability::class));

        Teams::createTeamsUsing(CreateTeam::class);
        Teams::updateTeamNamesUsing(UpdateTeamName::class);
        Teams::addTeamMembersUsing(AddTeamMember::class);
        Teams::inviteTeamMembersUsing(InviteTeamMember::class);
        Teams::removeTeamMembersUsing(RemoveTeamMember::class);
        Teams::deleteTeamsUsing(DeleteTeam::class);
        Teams::deleteUsersUsing(DeleteUser::class);
    }
}
```

**Comment by Jurager** [comment]
@fermevc @ZebTheWizard for now, in version 2.2 some changes done.

`TeamServiceProvider` in `config/app.php` is no longer required, it's need to be deleted. To simplify use of package and installation process, now by default package not publishing models to your application, it uses its own, 
you still have the ability to use your models by changing the configuration file.

It's was a bug with Group model not publishing during install process.

Group model was renamed to TeamGroup, you can use methods 

```php
// Get all groups of the team.
$team->groups()

// Add new group to the team
$team->addGroup(string $name)

// Delete group from the team
$team->deleteGroup(string $name)

```

Documentation for groups is almost ready, will update soon

**Comment by neoighodaro** [comment]
Just checking if you are still planning on documenting the Group feature? It's basically the reason I want to use this package as most others don't have this.

**Comment by Jurager** [comment]
@neoighodaro I've made some updates to the documentation and included details about team groups. Although we intended to implement this functionality in our project, it's currently undergoing testing. Hence, I would appreciate any feedback should any issues arise.

**Comment by neoighodaro** [comment]
> @neoighodaro I've made some updates to the documentation and included details about team groups. Although we intended to implement this functionality in our project, it's currently undergoing testing. Hence, I would appreciate any feedback should any issues arise.

Thank you! I’ll be sure to report anything I find. Have already some ideas for how to improve the package for example, I use UUIDs for my user IDs, so it doesn’t work out of the box for me. Possibly some config check or checking if `HasUuids` is on the model and automatically using `foreignUuid(…)` instead of `foreignId` for the fkeys

**Comment by neoighodaro** [comment]
Something missig is adding abilities to a group. I didn’t see that in the documentation but can figure that out, just as an FYI

**Comment by Jurager** [comment]
> Something missig is adding abilities to a group. I didn’t see that in the documentation but can figure that out, just as an FYI

Adding abilities to a group is described in readme

```
// Add an ability for user to action on certain model within team group, if permission is not found, will create a new one
$user->allowTeamAbility( Model $team, string 'server:edit', Model $server, Model $group));

// Forbid an ability for user to action on certain model within team group
$user->forbidTeamAbility(Model $team, string 'server:edit', Model $server, Model $group);

// Delete user ability to action on certain model within team group
$user->deleteTeamAbility(Model $team, string 'server:edit', Model $server, Model $group);
```
