### ISSUE TITLE
user migration is overwritten

### ISSUE THREAD

**Issue by rabol** [Jurager/teams#20]
When issuing the install command the users table migration is overwritten

now, while I do understand that new fields is needed on the user there is a few issues with the 'silent' approach :)

Installing the package in an exiting Laravel app will not work
If the migration has been executed before then publishing and overwriting the migration file does not have any effect
It's not mentioned in the doc, so one does not know that migration is needed.

It would be better to have a add_fields_to_users_table migration or document which new fields are needed

**Comment by Jurager** [comment]
Thanks for the feedback, indeed the user model was overwritten, corrected this mistake in the [https://github.com/Jurager/teams/commit/2445719605f3b51801cb031e8f045639fbabed5c](https://github.com/Jurager/teams/commit/2445719605f3b51801cb031e8f045639fbabed5c), will be available in new release soon.
