### ISSUE TITLE
Possible to use without groups?

### ISSUE THREAD

**Issue by PerryRylance** [Jurager/teams#22]
Hi

Great library, came here after becoming immensely frustrated with the Spatie experience.

Is it possible to use this library without groups?

We already have groups (of other models) which belong to our teams, so extending this libraries Team is problematic.

Thank you

**Comment by Jurager** [comment]
Hi @PerryRylance!

Yes, you can use your own model.  You can try to change default `Jurager\Teams\Models\Team::class` model in `config/teams.php` in `models.team` to point your actual model. Then copy to you model all methods from package's `Jurager\Teams\Models\Team::class` model, also change the `foreign_keys.team_id` to fit you "Team" model primary key.

**Comment by Jurager** [comment]
Relation from `User` to `Team` is implemented in `HasTeams` trait, you can see here the logic for accessing `Team` from User

```
    /**
     * Get all the teams the user belongs to.
     *
     * @return BelongsToMany
     */
    public function teams(): BelongsToMany
    {
        return $this->belongsToMany(Teams::$teamModel, Teams::$membershipModel)
            ->withPivot('role_id')
            ->withTimestamps()
            ->as('membership');
    }
```

**Comment by Jurager** [comment]
You also need to do the same with the `Membership` model, because it is used to indicate that the user is in the team, unless of course you already have your own mechanism, otherwise leave it as it is
