### ISSUE TITLE
Action CreateTeam::create gives error Call to undefined method Jurager\Teams\Teams::newTeamModel()

### ISSUE THREAD

**Issue by rabol** [Jurager/teams#23]
Hi

The documentation on how to use the actions could be better :)

I'm trying to create at new team:

```
        $action = new CreateTeam();
        $action->create(auth()->user(), $request->all());
```

But it fails with this error:

```
Call to undefined method Jurager\Teams\Teams::newTeamModel()
```

**Comment by ahseoai** [comment]
Hi @rabol, 
Has this project been abandoned since you're not receiving an answer?

**Comment by Jurager** [comment]
The documentation is poor, but problem was in action itself. Action checks user for ability to create team, but by default now this is not neccessary. Actions/CreateTeam.php need to be replaced with new version from package.
