### ISSUE TITLE
What's the status of this repo? 

### ISSUE THREAD

**Issue by ahseoai** [Jurager/teams#24]
Can we expect to see some elaborate documentation or are we supposed to guess our way forwards?
Nowhere does it say 

- how to add abilities
- how to add permissions
- how to add teams
- what the intended workflow should be
- how to use the supplied actions without errors
- how test this

Can we assume this is abandoned? If so, could you please inform on the readme that this is not intended for install.

Thanks in advance

**Comment by adgower** [comment]
Here is how to: add abilities/permissions/teams:
https://github.com/Jurager/teams/blob/2.0/README.md#roles--permissions

At the top of the package, it states the intended workflow:
"Laravel package to manage teams and operate with user permissions, abilities, supporting multi-tenant dynamic roles, roles groups, capabilities, and permissions for each team.

Users in teams can be combined into groups, with their own rights and permissions, access rights given to a user group overrides the rights granted to a user in a team."

Your ide should be able to pickup on the details on how to use an action with minimal error, ref this class for an example:
https://github.com/Jurager/teams/blob/2.0/stubs/app/Actions/Teams/CreateTeam.php

How to test:
https://laravel.com/docs/10.x/testing

Is there a specific issue you are having?

**Comment by tobz-nz** [comment]
I think what @ahseoai was meaning is there is it is not so clear how to use some things - like how to use actions for example.

I'd assume it'd be like:

```php
CreateTeam::create($user, [
    'name' => 'The A Team'
]);
```

but the `create` method is not static, so maybe its:

```php
(new CreateTeam)->create($user, [
    'name' => 'The A Team'
]);
```

Or is there some other class that is used to trigger an action?
It is not clear at all.
