### ISSUE TITLE
Issue with Team->users or allUsers

### ISSUE THREAD

**Issue by maosalah** [Jurager/teams#25]
I encountered an issue after installing the latest version. When attempting to retrieve all the users associated with the team, I received the following error message:

`Column not found: 1054 Unknown column 'team_user.role'.`

The migration specifies 'role_id' as the column name, but in the 'Team.php' model, it appears that you're trying to pivot using the 'role' column:

```
public function users(): BelongsToMany
{
    return $this->belongsToMany(Teams::$userModel, Teams::$membershipModel)
        ->withPivot('role')
        ->withTimestamps()
        ->as('membership');
}

```

This mismatch between the expected 'role_id' column and the 'role' column used in the model may be causing the issue.

**Comment by Jurager** [comment]
Thanks. Fixed in latest release
